<?php
namespace hollisho\httpclientTests\Client;

use hollisho\httpclient\BaseClient;
use Psr\Http\Message\ResponseInterface;

class HttpClient extends BaseClient
{
    public function httpPost(string $url, array $data = []): ResponseInterface
    {
        return parent::httpPost($url, $data); // TODO: Change the autogenerated stub
    }

}