<?php
namespace hollisho\httpclient\tests\Client;

use hollisho\httpclient\BaseClient;

class HttpClient extends BaseClient
{
    public function httpPost(string $url, array $data = [])
    {
        return parent::httpPost($url, $data); // TODO: Change the autogenerated stub
    }

}